# pytest-testmon-bug-none-in-cache
Trying to reproduce an issue with pytest-testmon mishandling __init__.py files in the cache
